# https://docs.travis-ci.com/user/environment-variables/
language: csharp
dotnet: 2.0.0

branches:
  only:
  - master

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database aspnetidentity;' -U postgres
  - psql -c 'CREATE USER aspnetidentity WITH PASSWORD 'aspnetidentity';' -U postgres
  - psql -c 'ALTER USER aspnetidentity WITH SUPERUSER;' -U postgres

script:
   - dotnet restore
   - dotnet build -c Release  
   - pushd src/MartenAspNetIdentity.Tests
   - dotnet test
   - popd
   - dotnet pack -c Release /p:PackageVersion=1.0.$TRAVIS_BUILD_NUMBER
   #- dotnet nuget push
